
<?php
/*	delete SOCIAL RELATION FORM */ 
?>

<div class="pure-form" style="height:300px; overflow:scroll;">
	<?php 
		$deleteSocialRelationForm = $this->deleteSocialRelationForm;
		//var_dump($deleteUserForm);
		$deleteSocialRelationForm -> prepare();

		// Set the id attribute for the form
		$deleteSocialRelationForm -> setAttribute('id', 'deleteSocialRelationForm');
		// Get the form label plugin
		$deleteSocialRelationFormLabel = $this->plugin('formLabel');
		// Get the user text field
		$startUserSelect= $deleteSocialRelationForm->get('contactCreatorUid');
		
	?>
	<div style="width:100%;">
    	<?php
        		// Rendering form elements
        		echo $this->form()->openTag($deleteSocialRelationForm);
        ?>
    	<div>
    	<?php
    		/*
    		 * START USER SELECT
    		 */
    		//label
    		echo $deleteSocialRelationFormLabel->openTag();
    		echo $startUserSelect->getLabel();
    		$startUserSelect    -> setAttribute ('onchange',"getContactListRequest('/users/get-user-contacts','contactList','startUid',1);return true;");
    		echo $deleteSocialRelationFormLabel->closeTag();
    		echo "&nbsp &nbsp";
    		
    		echo $this->formSelect($startUserSelect);
        ?>
        </div>
        
        <div style="height: 250px; overflow:scroll; float:right">
    		<!--  DESTINATION DIV for DYNAMIC FORM!-->
    		<div id='contactList' style='margin: 0 auto; height:200px; width:100%;'></div>
    		<div id='warning'></div>
    	</div>
    	<br>
    	<div style="float:right;margin-right:15px;">
    		<div class="pure-control-group">
    			<?php echo $this->formElement($deleteSocialRelationForm->get('send')); ?>
    		</div>
    	</div>
    	<?php echo $this->form()->closeTag() ?>
    </div>
</div>
