

<div id="accordion2">
    <!-- ********************  UNITS  ******************************* -->
    <h6>ADD SURVEYS</h6>
    <div>
        <?php echo "$this->addSurveysView"; ?>
    </div>
    <h6>DELETE SURVEYS</h6>
    <div>
        <?php echo "$this->deleteSurveysView"; ?>
    </div>

    <!-- ********************  CONTAINERS  ******************************* -->

    <h6>ADD CONTAINERS</h6>
    <div>
        <?php echo "$this->addContainersView"; ?>
    </div>
    <h6>DELETE CONTAINERS</h6>
    <div>
        <?php echo "$this->deleteContainersView"; ?>
    </div>
</div>
