<!--
/*
 * Application name: OpenRate-it!
 * A general-purpose polling platform
 * Copyright (C) 2014  Alain Bindele (alain.bindele@gmail.com)
 * This file is part of OpenRate-it!
 * OpenRate-it! is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * OpenRate-it! is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
-->


<div class="jumbotron" style="height:280px;">
<div style="position:absolute;z-index:-1; top:300px; left:0px; width:100%; height:300px; box-shadow:inset 0px 15px 15px #999; background:#bbb;"></div>
	<div style="
				float:right;
				height: 250px;
				width: 600px;
				position:relative;
				background-image:url(img/screenshot.png);
				filter:alpha(opacity=60); /* IE */
                -moz-opacity:0.6; /* Mozilla */
                opacity:0.6;
				top: -20px;
				right:-20px;
				-webkit-filter: blur(1px);
				background-repeat: no-repeat;
				opacity:0.5;
	">
	</div>
	<div  style="float:left;
	              z-index:2;
				position: absolute;
				vertical-position: 100px;">
		<div>
	    <h1><?php echo sprintf($this->translate('Welcome to %sOpenRate-it!%s'), '<span class="zf-green">', '</span>') ?></h1>
        </div>

	    <p><?php echo sprintf($this->translate('This is a general purpose Polling Platform'), '<a href="http://github.com/alainbindele/openrate-it/" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
	    <p><a class="btn btn-success btn-lg" href="https://github.com/alainbindele/openrate-it" target="_blank">Follow us on GitHub!</a></p>


	</div>

	          
<!-- Jssor Slider Begin -->
    <!-- You can move inline styles (except 'top', 'left', 'width' and 'height') to css file or css block. -->
    <div id="slider2_container" style="position: relative; margin:auto; width: 1200px; 
        height: 500px; top:-200px; overflow: hidden;">

         <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
            <div style="position: absolute; display: block; background: url(/img/load.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
        </div>
        

        <!-- Slides Container -->
        <div u="slides" style="border-radius:10px; cursor: move;box-shadow: 10px 10px 15px #888; position: relative; margin:auto; left: 400px; top: 50px; width: 600px; height: 300px;
            overflow: hidden;">
            <div>
            <img u="image" src="/img/slideshow/Screenshot1.png" />
                <div u="thumb" style="color: #fff;"><b>With OpenRate-it! you can store and retrieve surveys just about anything!.</b><br/>
                Which will be your next curiosity?<br /><br />
                <img src="/img/survey.png" style="float: left; margin-right: 8px; " height="36" width="36" />
                Many votes modalities: <b>Single, Multi, Shulze, Likert and Thumb</b>!
                </div>
            </div>

            <div>
                <img u="image" src="/img/slideshow/neo4j.png" />
                <div u="thumb">OpenRate-it! is born with efficiency in mind, so it use one of the most solid and efficient noSQL graph database: <a href="http://www.neo4j.org/">neo4j</a>
                </div>
            </div>
        </div>
        
        <!-- ThumbnailNavigator Skin Begin -->
        <div u="thumbnavigator" class="slider2-T" style="position: absolute; top: 200px; left: 0px; width:400px; height:200px;">
            <div style=" position: absolute; display: block;
                top: 100px; left: 0px; width: 300px; height: 100%;">
            </div>
            <!-- Thumbnail Item Skin Begin -->
            <div u="slides">
                <div u="prototype" style="POSITION: absolute; WIDTH: 350px; HEIGHT: 200px; top: 0; left: 100px;">
                    <thumbnailtemplate style="font-family: verdana; font-weight: normal; POSITION: absolute; WIDTH: 100%; HEIGHT: 100%; TOP: 0; LEFT: 0; color:#000; line-height: 22px; font-size:18px; padding: 5px;"></thumbnailtemplate>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
        </div>
        <!-- ThumbnailNavigator Skin End -->

        <!-- Bullet Navigator Skin Begin -->
        <!-- jssor slider bullet navigator skin 01 -->
        <style>
            /*
            .jssorb01 div           (normal)
            .jssorb01 div:hover     (normal mouseover)
            .jssorb01 .av           (active)
            .jssorb01 .av:hover     (active mouseover)
            .jssorb01 .dn           (mousedown)
            */
            .jssorb01 div, .jssorb01 div:hover, .jssorb01 .av
            {
            	 
                filter: alpha(opacity=70);
                opacity: .7;
                overflow:hidden;
                cursor: pointer;
                
            }
            .jssorb01 div {  background-color:#000; }
            .jssorb01 div:hover, .jssorb01 .av:hover { background-color: #d3d3d3; }
            .jssorb01 .av { background-color: #fff; }
            .jssorb01 .dn, .jssorb01 .dn:hover { background-color: #555555; }
        </style>
        <!-- bullet navigator container -->
        <br><br><br>
        <div u="navigator" class="jssorb01" style="clear:both;position: relative; margin-left:600px;padding-top:300px">
            <!-- bullet navigator item prototype -->
            <div u="prototype" style="POSITION: absolute; WIDTH: 11px; HEIGHT: 11px;"></div>
        </div>
        <!-- Bullet Navigator Skin End -->
        
        <!-- Arrow Navigator Skin Begin -->
        <style>
            /* jssor slider arrow navigator skin 05 css */
            /*
            .jssora05l              (normal)
            .jssora05r              (normal)
            .jssora05l:hover        (normal mouseover)
            .jssora05r:hover        (normal mouseover)
            .jssora05ldn            (mousedown)
            .jssora05rdn            (mousedown)
            */
            .jssora05l, .jssora05r, .jssora05ldn, .jssora05rdn
            {
            	position: absolute;
            	cursor: pointer;
            	display: block;
                background: url(/js/jssor/img/a17.png) no-repeat;
                overflow:hidden;
            }
            .jssora05l { background-position: -10px -40px; }
            .jssora05r { background-position: -70px -40px; }
            .jssora05l:hover { background-position: -130px -40px; }
            .jssora05r:hover { background-position: -190px -40px; }
            .jssora05ldn { background-position: -250px -40px; }
            .jssora05rdn { background-position: -310px -40px; }
        </style>
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssora05l" style=" -webkit-filter: invert(80%);  width: 40px; height: 40px; bottom: 80px; left: 400px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssora05r" style=" -webkit-filter: invert(80%);  width: 40px; height: 40px; bottom: 80px; right: 200px">
        </span>
        <!-- Arrow Navigator Skin End -->
        <a style="display: none" href="http://www.jssor.com">jQuery Slider</a>
        <!-- Trigger -->
    </div>
    <!-- Jssor Slider End -->


	
	
</div>

<div class="row" style="margin-top: 285px;">
    <div class="col-md-4" >
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Sapienza Apps') ?></h3>
            </div>
            <div class="panel-body" style="height:200px;">
                <p><?php echo sprintf($this->translate('OpenRate-it! is under development. If you are interested in following the development '), '<a href="http://www.sapienzaapps.it/rateit.php?c=3">', '</a>', '<a href="http://www.sapienzaapps.it/rateit.php?c=3">', '</a>', '<a http://www.sapienzaapps.it/rateit.php?c=3">', '</a>') ?></p>
                <div style="margin-top:100px;">
                <p><a class="btn btn-success pull-right" href="http://www.sapienzaapps.it/rateit.php?c=3" target="_blank"><?php echo $this->translate('Sapienza Apps portal') ?> &raquo;</a></p>
                </div>
                <div style="margin-top:-90px;">
                <img src="/img/sapienza_logo.png" width=100px>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body" style="height:200px;">
                <p><?php echo sprintf($this->translate('If you need any help or more informations about be and my work, you may take a look to the %sWIKI pages%s.<br> I\'d love to hear any questions or feedback you may have regarding the alpha release.'), '<a href="http://rate-it.dyndns.biz/mediawiki">', '</a>') ?></p>
                <div style="margin-top:40px;">
                    <p><a class="btn btn-success pull-right" href="http://rate-it.dyndns.biz/mediawiki" target="_blank"><?php echo $this->translate('WIKI pages') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
    </div> 
    
    
    
     <div class="col-md-4">
        <?php if($this->logged=='false'){?>
    	<div class="panel panel-default" >
    		<div class="panel-heading">
    			<h3 class="panel-title">
    	       <?php echo $this->translate('Login') ?></h3>
    		</div>
    		<div class="panel-body" style="height:200px;">
    			<a href="<?php echo $this->url('zfcuser') ?>"></a>
    			<div style="font-size:small; width:100%;" >
      			  <?php 
    				echo $this->zfcUserLoginWidget(); 
    			  ?>
    			</div>
    		</div>
    	</div>
    	<?php }else{?>
    	   	<div class="panel panel-default" >
        		<div class="panel-heading">
        			<h3 class="panel-title">
        	       <?php echo $this->translate('Welcome!') ?></h3>
        		</div>
        		<div class="panel-body" style="height:200px;">
        			<a href="<?php echo $this->url('zfcuser') ?>"></a>
        			<div style="font-size:small; width:100%;" >
        			<p>
          			  <?php 
        				echo sprintf($this->translate("Hello, <b>".$this->zfcUserDisplayName().",</b><br>")); 
        			  ?>
        			     You can start using this Application clicking the link in the upper-left corner: "Admin Panel".
        			     <br>
        			     Hope you enjoy this Application!
        			     
        			</p>
        			<div style="margin-top:65px;">
                    <p><a class="btn btn-success pull-right" href="/user/logout" target="_blank"><?php echo $this->translate('Logout') ?> &raquo;</a></p>
                    </div>
        			</div>
        		</div>
    	   </div>
    	<?php } ?>
    </div>
</div>
 <?php if($this->logged=='false'){?>
 <div id="presentation">
   <div style="filter: alpha(opacity=75); /* internet explorer */
			-khtml-opacity: 0.95;      /* khtml, old safari */
			-moz-opacity: 0.95;       /* mozilla, netscape */
			opacity: 0.95;           /* fx, safari, opera */
			height:100%;
			width:100%;
			position:absolute;
			left:0;
			top:0;
			z-index:4 !important;
			background-color:white;">
	   <div style="  
			margin:0px auto;
            position:relative;
            width:600px;">
    	   <div style="position:relative; top:150px; left:550px;  z-index:1;">
    		<img src="img/ico/minus.png" width=20 height=20 onclick="document.getElementById('presentation').innerHTML='';" >
    	   </div>
    	   <div style="position:relative;margin-top:150px;z-index:4;filter: alpha(opacity=100); /* internet explorer */
    		-khtml-opacity: 10.0;      /* khtml, old safari */
    		-moz-opacity: 10.0;       /* mozilla, netscape */
    		opacity: 10.0;           /* fx, safari, opera */"> 
    	   <iframe src="http://prezi.com/embed/bmhjrs0ma0my/?bgcolor=ffffff&amp;lock_to_path=0&amp;autoplay=1&amp;autohide_ctrls=0&amp;features=undefined&amp;disabled_features=undefined" width="550" height="400" frameBorder="0" webkitAllowFullScreen mozAllowFullscreen allowfullscreen></iframe>    
    	   </div>
	   </div>
   </div>
</div>
   <?php } ?>
