<!--
/*
 * Application name: OpenRate-it!
 * A general-purpose polling platform
 * Copyright (C) 2014  Alain Bindele (alain.bindele@gmail.com)
 * This file is part of OpenRate-it!
 * OpenRate-it! is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * OpenRate-it! is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
-->

<div style="width:100%;">
    <div style="text-align:center;width:50%;padding:20px;margin: 0px auto 0px auto;background-color:#eee;border-radius:6px;">

    <h1>Register</h1>
    
    <?php
    if (!$this->enableRegistration) {
        print "Registration is disabled";
        return;
    }
    $form = $this->registerForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/register'));
    $form->setAttribute('class','pure-form pure-form-aligned');
    $form->setAttribute('method', 'post');
    ?>
    <fieldset class="pure-control-group">
    <?php echo $this->form()->openTag($form) ?>
        
        <div class="pure-control-group">
        <?php foreach ($form as $element): ?>
            <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formLabel($element) ?>
            <?php endif ?>
            <?php if ($element instanceof Zend\Form\Element\Button): ?>
                <?php echo $this->formButton($element) ?>
            <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
            <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
                <?php echo $this->formSelect($element) . $this->formElementErrors($element); ?>
            <?php else: ?>
               <?php 
                    $element->setAttribute('class','pure-input-u-4-5');
                    echo $this->formInput($element) . $this->formElementErrors($element); 
                    ?>
            <?php endif ?>
        <?php
            echo "<br>"; 
            endforeach ?>
        </div>
        
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
    </fieldset>
    <?php echo $this->form()->closeTag() ?>
    </div>
<div>
