

<div id="accordion3">

    <!-- ************************************ ADD RATE **********************************************  -->
    <h6>RATE</h6>
    <div>
        <?php echo "$this->RatesView"; ?>
    </div>

    <!-- ************************************ ADD COMMENTS *******************************************  -->
    <h6>COMMENTS</h6>
    <div>
        <?php echo "$this->CommentsView"; ?>
    </div>
</div>
